# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  AdminUser: create, read, update, delete
  Ckeditor::Asset: create, read, update, delete
  Ckeditor::AttachmentFile: create, read, update, delete
  Ckeditor::Picture: create, read, update, delete
  CourseRegistration: create, read, update, delete
