# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

# Ckeditor::Asset:
#   fields:
#     default: data_file_name, assetable_id, guid, locale, user_id, user
#     form: data_file_name, assetable_id, guid, locale, user_id, user
#   order_by: 
#   relationships: user
#   filters: created_at
#   search: 
#   application: ofcourse

# Ckeditor::AttachmentFile:
#   fields:
#     default: data_file_name, assetable_id, guid, locale, user_id, user
#     form: data_file_name, assetable_id, guid, locale, user_id, user
#   order_by: 
#   relationships: user
#   filters: created_at
#   search: 
#   application: ofcourse

# Ckeditor::Picture:
#   fields:
#     default: data_file_name, assetable_id, guid, locale, user_id, user
#     form: data_file_name, assetable_id, guid, locale, user_id, user
#   order_by: 
#   relationships: user
#   filters: created_at
#   search: 
#   application: ofcourse

Course:
  fields:
    default: name,  description, date_of
    form: name, description, date_of, teacher
  order_by: 
  relationships: course_registrations, schedules, students, teacher
  filters: created_at
  search: name
  application: ofcourse

Room:
  fields:
    default: name
    form: name
  order_by: 
  relationships: schedules
  filters: created_at
  search: name
  application: ofcourse

# CourseRegistration:
#   fields:
#     default: user_id, course_id, course, user
#     form: user_id, course_id, course, user
#   order_by: 
#   relationships: course, user
#   filters: created_at
#   search: 
#   application: ofcourse

Role:
  fields:
    default: name, description
    form: name, description
  order_by: 
  relationships: users
  filters: created_at
  search: name
  application: ofcourse

Schedule:
  fields:
    default: start_date, end_date, start_time, end_time, monday, tuesday, wednesday, thursday, friday, saturday, sunday, period, course, room
    form: start_date, end_date, start_time, end_time, monday, tuesday, wednesday, thursday, friday, saturday, sunday, period, course, room
    options:
      selectors: period
    options:
      date_formats:
        start_time: time_of_day
        end_time: time_of_day
        start_date: nice_date
        end_date: nice_date
  order_by: 
  relationships: course
  filters: created_at
  search: 
  application: ofcourse

User:
  fields:
    default: email, remember_token, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
    form: email, reset_password_token, remember_token, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
  order_by: 
  relationships: course_registrations, courses, presentations, roles
  filters: created_at
  search: 
  application: ofcourse

